### ISSUE TITLE
Is is possible to set/read the configuration in a top level function when app is killed?

### ISSUE THREAD

**Issue by MilesAdamson** [Ephenodrom/Flutter-Global-Config#17]
I am currently setting my configuration in `main`, and everything works perfectly when the app is alive. When I kill the app though, I cannot seem to read the values of the configuration in a top level function.

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await GlobalConfiguration()
      .loadFromAsset(kReleaseMode ? "production.json" : "local.json");
```

In my case, this function is in a background task which fires every couple minutes the user is logged in, and needs to function properly when the app is killed. I have tried calling `loadFromAsset` from within this function but it still doesn't seem to work. If I hard code the value instead of reading from the config, it works properly so I'm quite sure this is the issue. Even though it's fairly annoying to get insight into what's going on when an app is killed. 

My background tasks works properly with GlobalConfiguration when the app is **not** killed.

This works:

```
  await dio.post(
    "https://hardcoded.redacted/v2/endpoint",
    data: {
      "example": [example]
    },
  );
```

This does not:

```
  String tenant = GlobalConfiguration().getString("tenant");
  await dio.post(
    "https://$tenant.redacted/v2/endpoint",
    data: {
      "example": [example]
    },
  );
```

Suggestions?

**Comment by Ephenodrom** [comment]
This is not possible, due to the GlobalConfiguration only loads the config when you initialize it. Once this is done, the configuration is then stored in a singleton and for that stored in the memory. Once the app is killed and you want to have access to it, i think you have to load the config again by initializing it. 

If you want to execute some code after receiving a push message, you will have to load the config again with:

```
await GlobalConfiguration()
      .loadFromAsset(kReleaseMode ? "production.json" : "local.json");
```
